name: Deploy App

on:
  workflow-dispatch:

jobs:
  deploy:
    environment:
      DOCKERHUB_USERNAME: ${{ vars.DOCKERHUB_USERNAME }}
    runs-on: self-hosted

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy with docker compose
        run: docker compose -d --build