#name of workflow
name: Matrix Workflow

on:
  workflow_dispatch: 

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Linter
        run: flake8 app.py
