# This is workflow name
name: Hello Nginx

on:
  workflow_dispatch: 

jobs:

  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Installing Nginx
        run: sudo apt-get install nginx

      - name: Nginx Installation Confirmation
        run: echo "Nginx Installed Successfully"
  
